joker = User.create(username: "joker", password: "make_up", email: "joker_man@jokeman.com")
ron = User.create(username: "ron_burgandy", password: "classy", email: "ron_b@anchorman.com")
tom = User.create(username: "tommy_boy", password: "schnikes", email: "tom_boy@tomboy.com")

joker.reminders.create(note: "Write 5 jokes", frequency: "daily")
joker.reminders.create(note: "Rob a bank", frequency: "weekly")
joker.reminders.create(note: "stay up late", frequency: "daily")
joker.reminders.create(note: "Go find mischief", frequency: "daily")

ron.reminders.create(note: "Drink a glass of scotch", frequency: "daily")
ron.reminders.create(note: "Throw a party", frequency: "weekly")
ron.reminders.create(note: "Play jazz flute", frequency: "monthly")
ron.reminders.create(note: "hangout with your buddies", frequency: "weekly")
ron.reminders.create(note: "get in an escalated fight", frequency: "weekly")
ron.reminders.create(note: "Give a news report accurately", frequency: "daily")
ron.reminders.create(note: "Go on a date in San Diego", frequency: "monthy")

tom.reminders.create(note: "Get to class on time", frequency: "daily")
tom.reminders.create(note: "Go cow tipping", frequency: "weekly")
tom.reminders.create(note: "make a ton of friends", frequency: "daily")
tom.reminders.create(note: "Get a sale for break pads", frequency: "daily")
tom.reminders.create(note: "Have dinner with dad", frequency: "weekly")
tom.reminders.create(note: "Have dinner with richard", frequency: "monthly")
tom.reminders.create(note: "try to learn something new on the business", frequency: "daily")